name: open-elevator
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - asgiref=3.4.1=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - blas=1.0=mkl
  - boto3=1.18.21=pyhd3eb1b0_0
  - botocore=1.21.21=pyhd3eb1b0_1
  - brotlipy=0.7.0=py38h7b6447c_1000
  - ca-certificates=2020.10.14=0
  - certifi=2021.5.30=py38h06a4308_0
  - cffi=1.14.3=py38he30daa8_0
  - chardet=3.0.4=py38_1003
  - click=8.0.1=py38h578d9bd_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.1.1=py38h1ba5d50_0
  - cycler=0.10.0=py_2
  - fastapi=0.68.0=pyhd8ed1ab_0
  - freetype=2.10.4=h0708190_1
  - h11=0.12.0=pyhd8ed1ab_0
  - hiredis=1.1.0=py38h1e0a361_1
  - icu=67.1=he1b5a44_0
  - idna=2.10=py_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jmespath=0.10.0=py_0
  - kiwisolver=1.3.1=py38h1fd1430_1
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py38h5d868c9_1
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.0=py38h42c9631_2
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.20.3=py38hf144106_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.0.1=py38h06a4308_0
  - pycparser=2.20=py_2
  - pydantic=1.8.2=py38h497a2fe_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py38_0
  - python=3.8.11=h12debd9_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - readline=8.1=h27cfd23_0
  - requests=2.24.0=py_0
  - s3transfer=0.5.0=pyhd3eb1b0_0
  - scipy=1.6.2=py38had2a1c9_1
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - starlette=0.14.2=pyhd8ed1ab_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.62.1=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - urllib3=1.25.11=py_0
  - uvicorn=0.15.0=py38h578d9bd_0
  - wheel=0.37.0=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - aiofiles==0.7.0
    - aioredis==2.0.0
    - fastapi-cache2==0.1.6
    - fastapi-limiter==0.1.4
    - ghp-import==2.0.1
    - importlib-metadata==4.6.4
    - jinja2==3.0.1
    - markdown==3.3.4
    - markupsafe==2.0.1
    - mergedeep==1.3.4
    - mkdocs==1.2.2
    - mkdocs-material==7.2.4
    - mkdocs-material-extensions==1.0.1
    - packaging==21.0
    - pygments==2.10.0
    - pymdown-extensions==8.2
    - pyyaml==5.4.1
    - pyyaml-env-tag==0.1
    - watchdog==2.1.4
    - zipp==3.5.0
prefix: /home/morpheus/anaconda3/envs/open-elevator

